In [2]:
#! pip install opencv-contrib-python
#! pip install numpy
#! pip install matplotlib

In [ ]:
import cv2

cv2.__version__

'4.12.0'

In [ ]:
img = cv2.imread("images/mi_foto.jpg")
print(img)

[[[175 175 175]
  [174 174 174]
  [175 175 175]
  ...
  [170 172 172]
  [172 172 172]
  [176 176 176]]

 [[175 175 175]
  [174 174 174]
  [175 175 175]
  ...
  [170 172 172]
  [172 172 172]
  [176 176 176]]

 [[175 175 175]
  [174 174 174]
  [175 175 175]
  ...
  [170 172 172]
  [172 172 172]
  [176 176 176]]

 ...

 [[159 168 178]
  [158 167 177]
  [155 170 179]
  ...
  [247 241 242]
  [247 242 243]
  [245 240 241]]

 [[162 171 181]
  [162 171 181]
  [156 171 180]
  ...
  [248 242 243]
  [247 242 243]
  [245 240 241]]

 [[164 173 183]
  [164 173 183]
  [156 171 180]
  ...
  [248 242 243]
  [248 243 244]
  [246 241 242]]]


In [5]:
print(img.shape)

(640, 484, 3)


In [ ]:
cv2.imshow("Opencv", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()

qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/jf/.pyenv/versions/3.11.8/envs/.venv/lib/python3.11/site-packages/cv2/qt/plugins"
QFont::fromString: Invalid description 'Noto Sans,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'


In [ ]:
import matplotlib.pyplot as plt

img = cv2.imread("images/mi_foto.jpg")
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img_rgb)
plt.axis("off")
plt.show()

In [ ]:
img = cv2.imread("images/mi_foto.jpg", cv2.IMREAD_GRAYSCALE)
print(img)
cv2.imwrite("images/mi_foto_gray.jpg", img)

[[175 174 175 ... 172 172 176]
 [175 174 175 ... 172 172 176]
 [175 174 175 ... 172 172 176]
 ...
 [170 169 171 ... 242 243 241]
 [173 173 172 ... 243 243 241]
 [175 175 172 ... 243 244 242]]


True

In [ ]:
import numpy as np

img = np.zeros((512, 512, 3))
# Imagen, coord-inicial, coord-final, BGR, grosor
cv2.rectangle(img, (200, 100), (300, 1), (255, 0, 255), -1)
cv2.imshow("new window", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [ ]:
# https://github.com/opencv/opencv/tree/master/data/haarcascades
# Download: https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xml
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
img = cv2.imread("images/mi_foto.jpg", 1)
faces = face_cascade.detectMultiScale(img, 1.1, 5)

for x, y, w, h in faces:
    print(x, y, w, h)
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 3)

cv2.imshow("colombiano", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()

128 122 183 183
